//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseSyncEntities : DbContext
    {
        public DatabaseSyncEntities()
            : base("name=DatabaseSyncEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StagingTransaction> StagingTransactions { get; set; }
        public virtual DbSet<StagingAccountDetail> StagingAccountDetails { get; set; }
        public virtual DbSet<StagingAccountIdentifier> StagingAccountIdentifiers { get; set; }
        public virtual DbSet<StagingAccount> StagingAccounts { get; set; }
        public virtual DbSet<StagingETCTransaction> StagingETCTransactions { get; set; }
        public virtual DbSet<StagingIncident> StagingIncidents { get; set; }
        public virtual DbSet<StagingTimeSlice> StagingTimeSlices { get; set; }
    
        public virtual ObjectResult<uspGetListOfSequenceNrGaps_Result> uspGetListOfSequenceNrGaps(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetListOfSequenceNrGaps_Result>("uspGetListOfSequenceNrGaps", fromParameter, toParameter);
        }
    }
}
