//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingTimeSlice
    {
        public string pl_id { get; set; }
        public string ln_id { get; set; }
        public int ts_seq_nr { get; set; }
        public Nullable<System.DateTime> dt_started { get; set; }
        public Nullable<System.DateTime> dt_ended { get; set; }
        public string us_id { get; set; }
        public string lm_id { get; set; }
        public Nullable<int> next_tx { get; set; }
        public Nullable<int> prev_tx { get; set; }
        public Nullable<int> tx_count { get; set; }
        public Nullable<int> next_inc { get; set; }
        public Nullable<int> prev_inc { get; set; }
        public Nullable<int> inc_count { get; set; }
        public Nullable<int> next_bo { get; set; }
        public Nullable<int> prev_bo { get; set; }
        public Nullable<int> bo_count { get; set; }
        public Nullable<int> next_sp { get; set; }
        public Nullable<int> prev_sp { get; set; }
        public Nullable<int> sp_count { get; set; }
        public Nullable<int> next_vat { get; set; }
        public Nullable<int> prev_vat { get; set; }
        public Nullable<int> vat_count { get; set; }
        public Nullable<int> next_avc { get; set; }
        public Nullable<int> prev_avc { get; set; }
        public Nullable<int> avc_count { get; set; }
        public Nullable<int> vgs_count { get; set; }
        public Nullable<int> ft_id { get; set; }
        public Nullable<int> pg_group { get; set; }
        public string loc_value { get; set; }
        public string cash_value { get; set; }
        public string sun_value { get; set; }
        public string stats_msg { get; set; }
        public Nullable<int> stats_count { get; set; }
        public Nullable<System.DateTime> ops_dt { get; set; }
        public Nullable<int> ops_sh { get; set; }
        public string vs_id { get; set; }
        public string rep_indic { get; set; }
        public string rd_id { get; set; }
        public string maint_indic { get; set; }
        public Nullable<int> req_indic { get; set; }
    }
}
