//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingIncident
    {
        public string pl_id { get; set; }
        public string ln_id { get; set; }
        public Nullable<System.DateTime> dt_generated { get; set; }
        public int in_seq_nr { get; set; }
        public string ir_type { get; set; }
        public string ir_subtype { get; set; }
        public Nullable<int> tx_seq_nr { get; set; }
        public Nullable<int> ts_seq_nr { get; set; }
        public string us_id { get; set; }
        public Nullable<int> ft_id { get; set; }
        public Nullable<int> pg_group { get; set; }
        public Nullable<int> cg_group { get; set; }
        public string vg_group { get; set; }
        public string mvc { get; set; }
        public string avc { get; set; }
        public string svc { get; set; }
        public Nullable<int> er_id { get; set; }
        public string pm_id { get; set; }
        public string card_nr { get; set; }
        public string mask_nr { get; set; }
        public string ca_id { get; set; }
        public string ct_id { get; set; }
        public string tx_indic { get; set; }
        public string lm_id { get; set; }
        public string as_id { get; set; }
        public string rep_indic { get; set; }
        public string rd_id { get; set; }
        public string maint_indic { get; set; }
        public Nullable<int> req_indic { get; set; }
        public Nullable<System.DateTime> ts_dt_started { get; set; }
        public string in_amt { get; set; }
        public string in_data { get; set; }
        public string tg_bl_id { get; set; }
        public string tg_mfg_id { get; set; }
        public string tg_card_type { get; set; }
        public string tg_reader { get; set; }
        public Nullable<int> tg_tx_seq_nr { get; set; }
        public Nullable<int> avc_in_seq_nr { get; set; }
        public Nullable<int> avc_in_type_id { get; set; }
        public Nullable<System.DateTime> avc_dt_generated { get; set; }
    }
}
