//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingAccountDetail
    {
        public string ac_nr { get; set; }
        public string ac_title { get; set; }
        public string ac_initial { get; set; }
        public string ac_surname { get; set; }
        public string ac_home_ph { get; set; }
        public string ac_work_ph { get; set; }
        public string ac_cell_ph { get; set; }
        public string ac_fax_ph { get; set; }
        public string ac_email { get; set; }
        public string at_id { get; set; }
        public string ac_password { get; set; }
    }
}
