//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingTransaction
    {
        public string pl_id { get; set; }
        public string ln_id { get; set; }
        public System.DateTime dt_concluded { get; set; }
        public int tx_seq_nr { get; set; }
        public Nullable<int> ts_seq_nr { get; set; }
        public string us_id { get; set; }
        public string ent_plz_id { get; set; }
        public string ent_lane_id { get; set; }
        public Nullable<System.DateTime> dt_started { get; set; }
        public Nullable<int> next_inc { get; set; }
        public Nullable<int> prev_inc { get; set; }
        public Nullable<int> ft_id { get; set; }
        public Nullable<int> pg_group { get; set; }
        public Nullable<int> cg_group { get; set; }
        public string vg_group { get; set; }
        public string mvc { get; set; }
        public string avc { get; set; }
        public string svc { get; set; }
        public string loc_curr { get; set; }
        public string loc_value { get; set; }
        public string ten_curr { get; set; }
        public string ten_value { get; set; }
        public string loc_change { get; set; }
        public string variance { get; set; }
        public Nullable<int> er_id { get; set; }
        public string pm_id { get; set; }
        public string card_nr { get; set; }
        public string mask_nr { get; set; }
        public string bin_nr { get; set; }
        public string serv_code { get; set; }
        public string ca_id { get; set; }
        public string ct_id { get; set; }
        public string it_id { get; set; }
        public string sec_card_nr { get; set; }
        public string lm_id { get; set; }
        public string as_id { get; set; }
        public string reg_nr { get; set; }
        public Nullable<int> vouch_nr { get; set; }
        public string ac_nr { get; set; }
        public string rec_nr { get; set; }
        public string tick_nr { get; set; }
        public Nullable<int> bp_id { get; set; }
        public Nullable<int> fg_id { get; set; }
        public Nullable<int> dg_id { get; set; }
        public string rd_id { get; set; }
        public string rep_indic { get; set; }
        public string maint_indic { get; set; }
        public Nullable<int> req_indic { get; set; }
        public string iv_prt_indic { get; set; }
        public Nullable<System.DateTime> ts_dt_started { get; set; }
        public Nullable<int> iv_nr { get; set; }
        public Nullable<int> td_id { get; set; }
        public Nullable<int> avc_seq_nr { get; set; }
        public string update_us_id { get; set; }
        public string card_bank { get; set; }
        public string card_ac_nr { get; set; }
        public string tg_mfg_id { get; set; }
        public string tg_post_bal { get; set; }
        public string tg_reader { get; set; }
        public string tg_us_cat { get; set; }
        public string tg_card_type { get; set; }
        public string tg_serv_prov_id { get; set; }
        public string tg_issuer { get; set; }
        public Nullable<int> tg_tx_seq_nr { get; set; }
        public string etc_context_mrk { get; set; }
        public Nullable<int> etc_manufac_id { get; set; }
        public Nullable<int> etc_beacon_id { get; set; }
        public string etc_contract_pv { get; set; }
        public Nullable<System.DateTime> avc_dt_concluded { get; set; }
        public string avc_status { get; set; }
        public string anpr_vln { get; set; }
        public Nullable<int> anpr_conf { get; set; }
        public string lvc { get; set; }
        public Nullable<int> inc_ind { get; set; }
        public string id_vl { get; set; }
        public string vl_vln { get; set; }
        public Nullable<int> anpr_seq_nr { get; set; }
    }
}
