//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingAccountIdentifier
    {
        public string ac_nr { get; set; }
        public string ri_id { get; set; }
        public string mask_nr { get; set; }
        public string it_id { get; set; }
        public string his_action { get; set; }
        public Nullable<System.DateTime> his_dt { get; set; }
        public string his_us_id { get; set; }
        public string his_change1 { get; set; }
        public string FullIdentifier { get; set; }
    }
}
