//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Database.Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingAccount
    {
        public string ac_nr { get; set; }
        public Nullable<int> ag_id { get; set; }
        public string rs_id { get; set; }
        public string ac_holder { get; set; }
        public Nullable<System.DateTime> ac_reg_dt { get; set; }
        public string ac_min_bal { get; set; }
        public Nullable<System.DateTime> ac_term_dt { get; set; }
        public string ac_term_rule { get; set; }
        public string ac_link_rule { get; set; }
        public string la_id { get; set; }
    }
}
