//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataRequest
    {
        public string LaneCode { get; set; }
        public string SequenceNumber { get; set; }
        public int Type { get; set; }
    }
}
