//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingRegisteredUser
    {
        public string Identifier { get; set; }
        public System.Guid AccountGuid { get; set; }
        public System.Guid AccountUserGuid { get; set; }
        public bool Reported { get; set; }
    }
}
