//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid SessionGUID { get; set; }
        public int SessionSeq { get; set; }
        public string LaneCode { get; set; }
        public System.Guid StaffLoginGUID { get; set; }
        public System.Guid LaneGUID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsSent { get; set; }
    
        public virtual StaffLogin StaffLogin { get; set; }
    }
}
