//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingMISAccountBalanceUpdate
    {
        public int Id { get; set; }
        public string MISAccountNr { get; set; }
        public System.Guid PCSAccountGuid { get; set; }
        public decimal OldBalance { get; set; }
        public decimal NewBalance { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateSentToMIS { get; set; }
    }
}
