//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.DataImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingMISValidationList
    {
        public long IDVL { get; set; }
        public long EFCMark { get; set; }
        public long PAN { get; set; }
        public int VehicleClass { get; set; }
        public int ProductType { get; set; }
        public string VLNPlateNo { get; set; }
        public System.DateTime VehicleStateDate { get; set; }
        public string VehicleState { get; set; }
    }
}
