//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.TollDataImport.DataRequest.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGroupsMapping
    {
        public int PaymentGroupCode { get; set; }
        public System.Guid PaymentGroupGUID { get; set; }
    }
}
