//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.TollDataImport.DataRequest.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCSIncident
    {
        public System.Guid IncidentGUID { get; set; }
        public System.Guid StaffLoginGUID { get; set; }
        public int IncidentSeqNr { get; set; }
        public System.Guid IncidentTypeGUID { get; set; }
        public System.DateTime IncidentSetDate { get; set; }
        public Nullable<System.DateTime> IncidentClearedDate { get; set; }
        public int LaneSeqNr { get; set; }
        public System.Guid IncidentStatusGUID { get; set; }
        public Nullable<System.DateTime> IncidentAckDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> TransactionGUID { get; set; }
        public Nullable<int> LastIncidentSeqNr { get; set; }
        public Nullable<bool> IsPermanetImagesSaved { get; set; }
        public string PermanetImagesURLs { get; set; }
    }
}
