//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.TollDataImport.DataRequest.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCSLane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCSLane()
        {
            this.Audits = new HashSet<PCSAudit>();
            this.Sessions = new HashSet<PCSSession>();
        }
    
        public System.Guid LaneGUID { get; set; }
        public System.Guid VirtualPlazaGUID { get; set; }
        public string LaneCode { get; set; }
        public string LaneDesc { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.Guid> LaneTypeGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCSAudit> Audits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCSSession> Sessions { get; set; }
    }
}
