//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.TollDataImport.DataRequest.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCSDBEntities : DbContext
    {
        public PCSDBEntities()
            : base("name=PCSDBEntities")
        {
    	((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PCSAudit> PCSAudits { get; set; }
        public virtual DbSet<PCSLane> PCSLanes { get; set; }
        public virtual DbSet<PCSIncident> PCSIncidents { get; set; }
        public virtual DbSet<PCSTransaction> PCSTransactions { get; set; }
        public virtual DbSet<PCSSession> PCSSessions { get; set; }
        public virtual DbSet<PCSStaffLogin> PCSStaffLogins { get; set; }
    }
}
