//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.TollDataImport.DataRequest.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PCSSVStagingEntities : DbContext
    {
        public PCSSVStagingEntities()
            : base("name=PCSSVStagingEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HourlyAudit> HourlyAudits { get; set; }
        public virtual DbSet<Lane> Lanes { get; set; }
        public virtual DbSet<ProcessedItem> ProcessedItems { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<StaffIdToGuidMapping> StaffIdToGuidMappings { get; set; }
        public virtual DbSet<StaffLogin> StaffLogins { get; set; }
        public virtual DbSet<TariffMapping> TariffMappings { get; set; }
        public virtual DbSet<PaymentGroupsMapping> PaymentGroupsMappings { get; set; }
        public virtual DbSet<PaymentMechMapping> PaymentMechMappings { get; set; }
        public virtual DbSet<PaymentMethodsMapping> PaymentMethodsMappings { get; set; }
        public virtual DbSet<PaymentTypesMapping> PaymentTypesMappings { get; set; }
        public virtual DbSet<UserMaping> UserMapings { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    
        public virtual ObjectResult<uspAccountUserDetailsGet_Result> uspAccountUserDetailsGet(string accountUserIdentifier)
        {
            var accountUserIdentifierParameter = accountUserIdentifier != null ?
                new ObjectParameter("AccountUserIdentifier", accountUserIdentifier) :
                new ObjectParameter("AccountUserIdentifier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspAccountUserDetailsGet_Result>("uspAccountUserDetailsGet", accountUserIdentifierParameter);
        }
    
        public virtual int uspCleanPCSStaging()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspCleanPCSStaging");
        }
    
        public virtual ObjectResult<uspGetSessionAfter_Result> uspGetSessionAfter(string laneCode, Nullable<System.DateTime> transactionTime)
        {
            var laneCodeParameter = laneCode != null ?
                new ObjectParameter("LaneCode", laneCode) :
                new ObjectParameter("LaneCode", typeof(string));
    
            var transactionTimeParameter = transactionTime.HasValue ?
                new ObjectParameter("TransactionTime", transactionTime) :
                new ObjectParameter("TransactionTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSessionAfter_Result>("uspGetSessionAfter", laneCodeParameter, transactionTimeParameter);
        }
    
        public virtual ObjectResult<uspGetSessionBefore_Result> uspGetSessionBefore(string laneCode, Nullable<System.DateTime> transactionTime)
        {
            var laneCodeParameter = laneCode != null ?
                new ObjectParameter("LaneCode", laneCode) :
                new ObjectParameter("LaneCode", typeof(string));
    
            var transactionTimeParameter = transactionTime.HasValue ?
                new ObjectParameter("TransactionTime", transactionTime) :
                new ObjectParameter("TransactionTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSessionBefore_Result>("uspGetSessionBefore", laneCodeParameter, transactionTimeParameter);
        }
    
        public virtual ObjectResult<uspGetSessionsToSlice_Result> uspGetSessionsToSlice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetSessionsToSlice_Result>("uspGetSessionsToSlice");
        }
    
        public virtual ObjectResult<uspSessionsGet_Result> uspSessionsGet(string laneCode)
        {
            var laneCodeParameter = laneCode != null ?
                new ObjectParameter("LaneCode", laneCode) :
                new ObjectParameter("LaneCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspSessionsGet_Result>("uspSessionsGet", laneCodeParameter);
        }
    
        public virtual ObjectResult<uspShiftsGet_Result> uspShiftsGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspShiftsGet_Result>("uspShiftsGet");
        }
    
        public virtual int uspShiftsInsert(Nullable<int> shift_Number, Nullable<System.DateTime> shift_StartTime, Nullable<System.DateTime> shift_EndTime, string shift_LaneCode, string staff_Identifier)
        {
            var shift_NumberParameter = shift_Number.HasValue ?
                new ObjectParameter("Shift_Number", shift_Number) :
                new ObjectParameter("Shift_Number", typeof(int));
    
            var shift_StartTimeParameter = shift_StartTime.HasValue ?
                new ObjectParameter("Shift_StartTime", shift_StartTime) :
                new ObjectParameter("Shift_StartTime", typeof(System.DateTime));
    
            var shift_EndTimeParameter = shift_EndTime.HasValue ?
                new ObjectParameter("Shift_EndTime", shift_EndTime) :
                new ObjectParameter("Shift_EndTime", typeof(System.DateTime));
    
            var shift_LaneCodeParameter = shift_LaneCode != null ?
                new ObjectParameter("Shift_LaneCode", shift_LaneCode) :
                new ObjectParameter("Shift_LaneCode", typeof(string));
    
            var staff_IdentifierParameter = staff_Identifier != null ?
                new ObjectParameter("Staff_Identifier", staff_Identifier) :
                new ObjectParameter("Staff_Identifier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspShiftsInsert", shift_NumberParameter, shift_StartTimeParameter, shift_EndTimeParameter, shift_LaneCodeParameter, staff_IdentifierParameter);
        }
    
        public virtual int uspUpdateIncident(Nullable<System.Guid> incidentGUID, Nullable<System.Guid> newStaffLoginGUID, ObjectParameter result)
        {
            var incidentGUIDParameter = incidentGUID.HasValue ?
                new ObjectParameter("IncidentGUID", incidentGUID) :
                new ObjectParameter("IncidentGUID", typeof(System.Guid));
    
            var newStaffLoginGUIDParameter = newStaffLoginGUID.HasValue ?
                new ObjectParameter("NewStaffLoginGUID", newStaffLoginGUID) :
                new ObjectParameter("NewStaffLoginGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateIncident", incidentGUIDParameter, newStaffLoginGUIDParameter, result);
        }
    
        public virtual int uspUpdateTransaction(Nullable<System.Guid> transactionGUID, Nullable<System.Guid> newSessionGUID, ObjectParameter result)
        {
            var transactionGUIDParameter = transactionGUID.HasValue ?
                new ObjectParameter("TransactionGUID", transactionGUID) :
                new ObjectParameter("TransactionGUID", typeof(System.Guid));
    
            var newSessionGUIDParameter = newSessionGUID.HasValue ?
                new ObjectParameter("NewSessionGUID", newSessionGUID) :
                new ObjectParameter("NewSessionGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateTransaction", transactionGUIDParameter, newSessionGUIDParameter, result);
        }
    
        public virtual int uspUpdateTransactionIncidentSession(Nullable<System.Guid> oldSessionGUID, Nullable<System.Guid> newSessionGUID)
        {
            var oldSessionGUIDParameter = oldSessionGUID.HasValue ?
                new ObjectParameter("OldSessionGUID", oldSessionGUID) :
                new ObjectParameter("OldSessionGUID", typeof(System.Guid));
    
            var newSessionGUIDParameter = newSessionGUID.HasValue ?
                new ObjectParameter("NewSessionGUID", newSessionGUID) :
                new ObjectParameter("NewSessionGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateTransactionIncidentSession", oldSessionGUIDParameter, newSessionGUIDParameter);
        }
    
        public virtual int uspUpdateValidationListItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateValidationListItems");
        }
    
        public virtual ObjectResult<uspGetAuditByLaneAndHour_Result> uspGetAuditByLaneAndHour(Nullable<int> laneID, Nullable<System.DateTime> auditDate, Nullable<int> auditHour)
        {
            var laneIDParameter = laneID.HasValue ?
                new ObjectParameter("LaneID", laneID) :
                new ObjectParameter("LaneID", typeof(int));
    
            var auditDateParameter = auditDate.HasValue ?
                new ObjectParameter("AuditDate", auditDate) :
                new ObjectParameter("AuditDate", typeof(System.DateTime));
    
            var auditHourParameter = auditHour.HasValue ?
                new ObjectParameter("AuditHour", auditHour) :
                new ObjectParameter("AuditHour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAuditByLaneAndHour_Result>("uspGetAuditByLaneAndHour", laneIDParameter, auditDateParameter, auditHourParameter);
        }
    
        public virtual ObjectResult<uspIncidentTypesGet_Result> uspIncidentTypesGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspIncidentTypesGet_Result>("uspIncidentTypesGet");
        }
    
        public virtual ObjectResult<uspGetTransactionByLaneAndSeq_Result> uspGetTransactionByLaneAndSeq(Nullable<int> laneID, Nullable<int> sequenceNumber)
        {
            var laneIDParameter = laneID.HasValue ?
                new ObjectParameter("LaneID", laneID) :
                new ObjectParameter("LaneID", typeof(int));
    
            var sequenceNumberParameter = sequenceNumber.HasValue ?
                new ObjectParameter("SequenceNumber", sequenceNumber) :
                new ObjectParameter("SequenceNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetTransactionByLaneAndSeq_Result>("uspGetTransactionByLaneAndSeq", laneIDParameter, sequenceNumberParameter);
        }
    
        public virtual ObjectResult<uspGetIncidentByLaneAndSeq_Result> uspGetIncidentByLaneAndSeq(Nullable<int> laneID, Nullable<int> sequenceNumber)
        {
            var laneIDParameter = laneID.HasValue ?
                new ObjectParameter("LaneID", laneID) :
                new ObjectParameter("LaneID", typeof(int));
    
            var sequenceNumberParameter = sequenceNumber.HasValue ?
                new ObjectParameter("SequenceNumber", sequenceNumber) :
                new ObjectParameter("SequenceNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetIncidentByLaneAndSeq_Result>("uspGetIncidentByLaneAndSeq", laneIDParameter, sequenceNumberParameter);
        }
    }
}
