//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.PCS.DataIntergration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lane
    {
        public int ID { get; set; }
        public string LaneCode { get; set; }
        public System.Guid LaneGuid { get; set; }
        public string LaneIP { get; set; }
    }
}
