//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.PCS.DataIntergration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffLogin()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public System.Guid StaffLoginGUID { get; set; }
        public System.Guid StaffGUID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid RoleGUID { get; set; }
        public System.Guid LocationGUID { get; set; }
        public System.Guid LocationTypeGUID { get; set; }
        public string ApplicationID { get; set; }
        public string IpAddress { get; set; }
        public string TerminalID { get; set; }
        public bool SupervisorOnDuty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
