//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.PCS.DataIntergration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffMapping
    {
        public int Id { get; set; }
        public int TollTariffPlanID { get; set; }
        public int VirtualPlazaID { get; set; }
        public int ClassCode { get; set; }
        public System.Guid TariffGuid { get; set; }
    }
}
