//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertoll.PCS.DataIntergration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Transaction_Identifier { get; set; }
        public string LaneCode { get; set; }
        public System.DateTime TransactionStartDate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.Guid> CollectorClass { get; set; }
        public Nullable<System.Guid> AVCClass { get; set; }
        public decimal TariffAmount { get; set; }
        public string LaneStatus { get; set; }
        public string Shift_Identifier { get; set; }
        public int CollectorID { get; set; }
        public int LaneTransSeqNr { get; set; }
        public int AVCSeqNr { get; set; }
        public string AvcStatus { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentGroup { get; set; }
        public string PaymentMech { get; set; }
        public string PaymentType { get; set; }
        public string BankCardNumber { get; set; }
        public string BankCardExpiryDate { get; set; }
        public string LicensePlate { get; set; }
        public string TaxInvNr { get; set; }
        public Nullable<int> ReceiptCount { get; set; }
        public string FrequentUserPANNumber { get; set; }
        public Nullable<bool> IsKeyed { get; set; }
        public Nullable<System.DateTime> ReceiptTaxInvoiceDate { get; set; }
        public string ANPRLicensePlate { get; set; }
        public Nullable<System.Guid> ETCTransactionGUID { get; set; }
        public string ContextMark { get; set; }
        public string PAN { get; set; }
        public Nullable<long> IDVL { get; set; }
        public string TagStatus { get; set; }
        public Nullable<int> TagClass { get; set; }
        public Nullable<System.Guid> OperatorAuthenticatorGuid { get; set; }
        public string OperatorAuthenticator_KSID { get; set; }
        public string OperatorAuthenticator_KV { get; set; }
        public string OperatorAuthenticator_KRef { get; set; }
        public string OperatorAuthenticator_DData { get; set; }
        public string OperatorAuthenticator_DMAC { get; set; }
        public string OperatorAuthenticator_MAC { get; set; }
        public Nullable<System.Guid> IssuerAuthenticatorGuid { get; set; }
        public string IssuerAuthenticator_KSID { get; set; }
        public string IssuerAuthenticator_KV { get; set; }
        public string IssuerAuthenticator_KRef { get; set; }
        public string IssuerAuthenticator_DData { get; set; }
        public string IssuerAuthenticator_DMAC { get; set; }
        public string IssuerAuthenticator_MAC { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<bool> Duplicate { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid TransGuid { get; set; }
        public System.Guid SessionGuid { get; set; }
        public Nullable<int> ContextMarkId { get; set; }
        public Nullable<System.Guid> AccountUserGUID { get; set; }
        public System.Guid TariffGuid { get; set; }
        public Nullable<long> TAGEFCM { get; set; }
        public Nullable<int> TAGMAID { get; set; }
        public Nullable<long> TAGOBUID { get; set; }
    }
}
