//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineImages
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionImage
    {
        public System.Guid TransactionImageGUID { get; set; }
        public System.Guid TransGUID { get; set; }
        public System.DateTime ImageDate { get; set; }
        public byte[] Image { get; set; }
        public string LicensePlate { get; set; }
    }
}
