CREATE TABLE [dbo].[StagingTimeSlices] (
    [pl_id]       VARCHAR (9)  NULL,
    [ln_id]       VARCHAR (9)  NOT NULL,
    [ts_seq_nr]   INT          NOT NULL,
    [dt_started]  DATETIME     NULL,
    [dt_ended]    DATETIME     NULL,
    [us_id]       VARCHAR (31) NULL,
    [lm_id]       VARCHAR (2)  NULL,
    [next_tx]     INT          NULL,
    [prev_tx]     INT          NULL,
    [tx_count]    INT          NULL,
    [next_inc]    INT          NULL,
    [prev_inc]    INT          NULL,
    [inc_count]   INT          NULL,
    [next_bo]     INT          NULL,
    [prev_bo]     INT          NULL,
    [bo_count]    INT          NULL,
    [next_sp]     INT          NULL,
    [prev_sp]     INT          NULL,
    [sp_count]    INT          NULL,
    [next_vat]    INT          NULL,
    [prev_vat]    INT          NULL,
    [vat_count]   INT          NULL,
    [next_avc]    INT          NULL,
    [prev_avc]    INT          NULL,
    [avc_count]   INT          NULL,
    [vgs_count]   INT          NULL,
    [ft_id]       INT          NULL,
    [pg_group]    INT          NULL,
    [loc_value]   VARCHAR (50) NULL,
    [cash_value]  VARCHAR (50) NULL,
    [sun_value]   VARCHAR (50) NULL,
    [stats_msg]   VARCHAR (31) NULL,
    [stats_count] INT          NULL,
    [ops_dt]      DATE         NULL,
    [ops_sh]      INT          NULL,
    [vs_id]       VARCHAR (2)  NULL,
    [rep_indic]   VARCHAR (2)  NULL,
    [rd_id]       VARCHAR (2)  NULL,
    [maint_indic] VARCHAR (2)  NULL,
    [req_indic]   INT          NULL,
    CONSTRAINT [PK_StagingTimeSlices] PRIMARY KEY CLUSTERED ([ln_id] ASC, [ts_seq_nr] ASC)
);



